name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unit:
    name: ${{ matrix.os }} jdk-${{ matrix.java }} unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        java: [8, 11]
        exclude:
          - os: macOS-latest
            java: 8
        include:
          - os: ubuntu-latest
            CACHE_PATH: ~/.cache/coursier/v1
          - os: macOS-latest
            CACHE_PATH: ~/Library/Caches/Coursier/v1
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.9.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - uses: actions/cache@v3.0.8
        with:
          path: $CACHE_PATH
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - uses: actions/cache@v3.0.8
        with:
          path: ~/.sbt
          key: |
            ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}-${{ hashFiles('project/plugins.sbt') }}
          restore-keys: ${{ runner.os }}-sbt-
      - run: sbt test
        shell: bash
