name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  unit:
    name: ${{ matrix.os }} jdk-${{ matrix.java }} unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        java: [8, 11]
        exclude:
          - os: macOS-latest
            java: 8
        include:
          - os: ubuntu-latest
            CACHE_PATH: ~/.cache/coursier/v1
          - os: macOS-latest
            CACHE_PATH: ~/Library/Caches/Coursier/v1
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - run: brew uninstall --ignore-dependencies python@3.9 python@3.8
        if: matrix.os == 'macOS-latest'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install virtualenv
      - uses: actions/cache@v2.1.5
        with:
          path: $CACHE_PATH
          key: ${{ runner.os }}-coursier-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-
      - uses: actions/cache@v2.1.5
        with:
          path: ~/.sbt
          key: |
            ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}-${{ hashFiles('project/plugins.sbt') }}
          restore-keys: ${{ runner.os }}-sbt-
      - uses: actions/cache@v2.1.5
        with:
          path: tests/slow/target/pants
          key: ${{ runner.os }}-pants-repo-${{ hashFiles('project/PantsRepo.scala') }}-1
          restore-keys: ${{ runner.os }}-pants-repo-${{ hashFiles('project/PantsRepo.scala') }}-1
      - uses: actions/cache@v2.1.5
        with:
          path: ~/.cache/pants
          key: ${{ runner.os }}-pants-cache
          restore-keys: ${{ runner.os }}-pants-cache
      - run: pip install virtualenv
        shell: bash
      - run: sbt test
        shell: bash
