name: Native Image
on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]
jobs:
  native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        include:
          - os: macOS-latest
            artifact: fastpass-x86_64-apple-darwin
          - os: ubuntu-latest
            artifact: fastpass-x86_64-pc-linux
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: graalvm-ce-java11@20.1.0
      - run: git fetch --tags || true
      - run: gu install native-image
      - run: sbt native-image
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.artifact }}
          path: fastpass/target/graalvm-native-image/fastpass
      - name: Upload release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: fastpass/target/graalvm-native-image/fastpass
          asset_name: ${{ matrix.artifact }}
          asset_content_type: application/zip
