name: Release
on:
  push:
    branches: [master]
    tags: ["*"]
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.9.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: olafurpg/setup-gpg@v3
      - run: git fetch --tags || true
      - name: Publish ${{ github.ref }}
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
